version: 0.2

phases:
  install:
    commands:
      - curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION  --no-include-email)
  build:
    commands:
      - echo Building the Docker image...
      - docker-compose build
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker-compose push
      - echo Sending notification...
      - aws sns publish --topic-arn "$SNS_TOPIC_ARN" --subject "AWS CodeBuild $CODEBUILD_BUILD_ID" --message "Build Completed"
      #- aws sns publish --topic-arn "$SNS_TOPIC_ARN" --subject "AWS CodeBuild - Build Completed - $CODEBUILD_BUILD_ID" --message "Build Completed"
      #- aws sns publish --topic-arn "$SNS_TOPIC_ARN" --subject "AWS CodeBuild - Build Completed" --message "Build Completed"
      #- aws sns publish --topic-arn "$SNS_TOPIC_ARN" --subject "AWS CodeBuild - Build Completed" --message "https://console.aws.amazon.com/cloudwatch/home?region=${AWS_DEFAULT_REGION}#logStream:group=/aws/codebuild/${BUILD_PROJECT_NAME}"
      #- aws sns publish --topic-arn "$SNS_TOPIC_ARN" --subject "AWS CodeBuild - Build Completed - Status: $CODEBUILD_BUILD_SUCCEEDING" --message "https://console.aws.amazon.com/cloudwatch/home?region=$AWS_DEFAULT_REGION#logStream:group=/aws/codebuild/$BUILD_PROJECT_NAME"
