AWSTemplateFormatVersion: "2010-09-09"
Description: CodeBuild Docker Project Sample


Parameters:
  GitHubRepo:
    Type: String
    Default: https://github.com/{USERNAME}/{REPOSITORY_NAME}.git
  SnsTopicNameForCodebuildProject:
    Type: String

Resources:

  CodeBuildDockerWebapp:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-project
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepo
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/docker:17.09.0
        ComputeType: BUILD_GENERAL1_LARGE
        EnvironmentVariables:
        - Name: AWS_ACCOUNT_ID
          Value: !Ref AWS::AccountId
        - Name: IMAGE_REPO_PREFIX
          Value: codebuild/test
        - Name: SNS_TOPIC_ARN
          Value: !Ref SnsTopicNameForCodebuildProject
      ServiceRole: !GetAtt [ IamRoleForCodeBuild, Arn ]

  ## ----------------------------------------------------------------------------

  EcrRepositoryWebapp:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: codebuild/test/webapp

  EcrRepositoryNginx:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: codebuild/test/nginx

  ## ----------------------------------------------------------------------------

  IamRoleForCodeBuild:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-iam-role-codebuild
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: policy-for-codebuild
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: [
                  "logs:CreateLogGroup",
                  "logs:CreateLogStream",
                  "logs:PutLogEvents",
                  "logs:DescribeLogStreams"]
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action: [
                  "ecr:BatchCheckLayerAvailability",
                  "ecr:GetDownloadUrlForLayer",
                  "ecr:GetRepositoryPolicy",
                  "ecr:DescribeRepositories",
                  "ecr:ListImages",
                  "ecr:DescribeImages",
                  "ecr:BatchGetImage",
                  "ecr:CompleteLayerUpload",
                  "ecr:GetAuthorizationToken",
                  "ecr:InitiateLayerUpload",
                  "ecr:PutImage",
                  "ecr:UploadLayerPart"]
                Resource: "*"
              - Effect: Allow
                Action: ["sns:Publish"]
                Resource: "*"

